# Generated by Django 2.1.2 on 2018-10-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_traded', models.CharField(max_length=3)),
                ('currency_quoted', models.CharField(max_length=3)),
                ('period_interval', models.CharField(max_length=3)),
                ('period_start_timestamp', models.CharField(max_length=50)),
                ('period_low', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_open', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_close', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_high', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_volume', models.DecimalField(decimal_places=10, max_digits=25)),
                ('data_source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCandleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_traded', models.CharField(max_length=3)),
                ('currency_quoted', models.CharField(max_length=3)),
                ('period_interval', models.CharField(max_length=3)),
                ('period_start_timestamp', models.CharField(max_length=50)),
                ('period_low', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_open', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_close', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_high', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_volume_currency_traded', models.DecimalField(decimal_places=10, max_digits=25)),
                ('period_volume_currency_quoted', models.DecimalField(decimal_places=10, max_digits=25)),
                ('weighted_price', models.DecimalField(decimal_places=10, max_digits=25)),
                ('data_source', models.CharField(max_length=255)),
            ],
        ),
    ]
