# Generated by Django 2.1.2 on 2018-10-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocandle',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 10, 2, 2, 626664)),
        ),
        migrations.AddField(
            model_name='cryptocandlehistory',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 10, 2, 2, 627989)),
        ),
    ]
