# Generated by Django 2.1.2 on 2018-10-18 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_track', '0004_auto_20181018_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocandle',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 14, 21, 43, 305053, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cryptocandlehistory',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 14, 21, 43, 306451, tzinfo=utc)),
        ),
    ]
