# Generated by Django 2.1.2 on 2018-10-18 14:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_track', '0005_auto_20181018_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocandle',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 14, 23, 53, 283497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cryptocandlehistory',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 18, 14, 23, 53, 284412, tzinfo=utc)),
        ),
    ]
