# Generated by Django 2.1.2 on 2018-10-26 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_track', '0007_auto_20181018_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocandle',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 9, 20, 15, 809752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cryptocandlehistory',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 9, 20, 15, 810501, tzinfo=utc)),
        ),
    ]
