# Generated by Django 2.1.2 on 2018-10-30 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_track', '0010_auto_20181029_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocandle',
            name='trend_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto_track.PyTrends'),
        ),
        migrations.AlterField(
            model_name='cryptocandle',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 12, 19, 57, 587809, tzinfo=utc)),
        ),
    ]
