# Generated by Django 2.1.2 on 2018-10-31 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_track', '0011_auto_20181030_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocandle',
            old_name='trend_date',
            new_name='search_trend',
        ),
        migrations.AlterField(
            model_name='cryptocandle',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 11, 44, 34, 824177, tzinfo=utc)),
        ),
    ]
