# Generated by Django 2.1.2 on 2018-11-01 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_track', '0012_auto_20181031_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocandle',
            name='signal',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='cryptocandle',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 11, 37, 23, 20121, tzinfo=utc)),
        ),
    ]
