# Generated by Django 2.1.2 on 2018-11-01 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_track', '0013_auto_20181101_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocandle',
            name='bank',
            field=models.DecimalField(decimal_places=10, max_digits=25, null=True),
        ),
        migrations.AddField(
            model_name='cryptocandle',
            name='prior_period_candle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto_track.CryptoCandle'),
        ),
        migrations.AlterField(
            model_name='cryptocandle',
            name='update_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 13, 15, 1, 520687, tzinfo=utc)),
        ),
    ]
